### ISSUE TITLE
SE Comment Link Helper: or reuse the scheme of current page 

### ISSUE THREAD

**Issue by tophf** [rchern/StackExchangeScripts#74]
Currently `SE Comment Link Helper` [doesn't alter](https://github.com/rchern/StackExchangeScripts/blob/a0b55b0a906b8526512125643db7ea2400593347/SECommentLinkHelper.user.js#L136) http scheme on links obtained from e.g. Share button under an answer.

Since StackOverflow and some other SE sites support HTTPS, I suggest using `location.protocol` in the code instead.

**Comment by tms** [comment]
Since the comment markdown will accept schemeless links now a la `[text](//url)`, the script will now generate that format for the scheme-of-choice benefit of the comment reader
