### ISSUE TITLE
Comment Helper Not working.

### ISSUE THREAD

**Issue by DavidPostill** [rchern/StackExchangeScripts#75]
Windows 7 Home Premium 64 bit, Firefox 49.0.1

Has stopped working today.

Possible cause SE jQuery update?

https://meta.stackexchange.com/questions/284996/we-have-updated-jquery-to-1-12-4-please-report-related-bugs-here?cb=1

**Comment by tms** [comment]
Indeed! Should be fixed now, please update and let me know if you run into any more issues
