### ISSUE TITLE
SEChatModifications: Icons sprite sheet not loading.

### ISSUE THREAD

**Issue by Cerbrus** [rchern/StackExchangeScripts#77]
This url appears to be broken:

http://or.sstatic.net/chat/img/leave-and-switch-icons.png

It's used on [line 1563 of SEChatModifications](https://github.com/rchern/StackExchangeScripts/blob/master/SEChatModifications.user.js#L1563).  
Instead of a nice icon, a chat message now shows a white square on hover:

![capture](https://cloud.githubusercontent.com/assets/2911988/23059355/618bc012-f4f9-11e6-884b-ac2bc64d5b29.PNG)

**Comment by tms** [comment]
Fixed in #78
