### ISSUE TITLE
SE Comment Link Helper: always link to https://

### ISSUE THREAD

**Issue by mjpieters** [rchern/StackExchangeScripts#86]
Issue #74 moved the comment helper to using protocol-relative URLs, but such URLs are [explicitly excluded from becoming *linked posts*](https://meta.stackexchange.com/questions/291236/protocol-relative-and-relative-urls-should-be-considered-linked).

Now that the HTTPS rollout of the SE network is complete, can the comment helper be updated to use `http://` at the start of URLs?

**Comment by Rubiksmoose** [comment]
This would be great. I came here to recommend the same thing.

**Comment by tms** [comment]
Super slow on the draw here, but yes. It's a bit unfortunate since we were saving five characters per link with the protocol-relative option, but I think the more important thing is to be correct. I'll make the change later today, thanks!
