### ISSUE TITLE
SE comment helper: [sitename].meta.stackexchange.com links are not handled.

### ISSUE THREAD

**Issue by mjpieters** [rchern/StackExchangeScripts#87]
During the big SSL changeover, Meta sites moved from `meta.[site].stackexchange.com` to `[site].meta.stackexchange.com`, see  [*Why are per-site metas under the meta.stackexchange domain instead of their main site's domain?*](https://meta.stackexchange.com/q/322560)

But the [`validSites` regexp](https://github.com/rchern/StackExchangeScripts/blob/master/SECommentLinkHelper.user.js#L44) regards those links as invalid, only `meta.[site].stackexchange.com` is sanctioned.

Can this be updated so we can link to per-site meta posts on all sites in the network?

**Comment by ron-reaser** [comment]
I believe the corrected regex should be as follows:
`^(?:(?:(?:meta\.)?(?:stackoverflow|serverfault|askubuntu|superuser))|(?:[^.]+\.(?:meta\.)?stackexchange)|stackapps)\.com$`
